#!/bin/bash

set -e

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{{ user_yum_root_dir }}/usr/lib:{{ user_yum_root_dir }}/usr/lib64:{{ user_yum_root_dir }}/usr/lib64/iscsi:{{ user_yum_root_dir }}/usr/lib64/pulseaudio"

{{ user_yum_root_dir }}/usr/bin/qemu-system-i386 "$@"
